apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-final-aug14-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-final-aug14-1:139361c453936acf36c98132c99452e07a049f7c@sha256:13c2d5d55c7e3cced9a9aa669fa5c49459814a8e5d7cc351cc69f9ccdf21e784 # use pre-built to bootstrap 
          name: app-inference
